server:
  port: 8080  #当前 Eureka Server 服务端⼝
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心的访问地址
spring:
  application:
    name: configclient  #当前服务注册在 Eureka Server 上的名称